version: 2.1

jobs:
  tracedb-rust:
    docker:
      - image: cimg/rust:1.89
    environment:
      RUSTFLAGS: "-A warnings"
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}
            - cargo-v1-
      - run:
          name: Check
          command: cargo check
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo/registry
            - ~/.cargo/git
            - target

workflows:
  ci:
    jobs:
      - tracedb-rust:
          name: circleci/tracedb-rust
          filters:
            tags:
              only: /^v.*/
